##
## Clean all output files generated by the experimentation code
##

unlink("exdata", recursive = T)
unlink("slurmOut", recursive = T)
unlink(".Rproj.user/", recursive = T)
unlink("*.pdf")
unlink("*.rds")
unlink(".RData")
unlink(".Rhistory")


